# CLASS .ini template for LCDM + Geff code.

## Precision Parameters
k_per_decade_for_pk = 50
k_bao_width = 8
k_per_decade_for_bao = 200
neglect_CMB_sources_below_visibility = 1e-30
transfer_neglect_late_source = 3000.0
l_max_g = 50
l_max_ur = 150
gauge = synchronous


## Cosmological Parameters
h = 
A_s =  ## Rescaled to match massive neutrinos
n_s = 

Omega_cdm = 
Omega_b = 
Omega_k = 0
Omega_fld = 0.0


alpha_s = 0.0
T_cmb = 2.7255
N_ur = 3.044


## Output parameters

output = dTk vTk mPk
root = 
P_k_max_h/Mpc = 
z_max_pk = 100.0
z_pk = 99.0, 4.0, 3.0, 2.0
extra metric transfer functions = y

## Geff
#N_ncdm = 0
#m_ncdm = 
log10_G_eff_nu = 
