# CLASS .ini template for LCDM + Geff code.

## Precision Parameters
k_per_decade_for_pk = 50
k_bao_width = 8
k_per_decade_for_bao = 200
neglect_CMB_sources_below_visibility = 1e-30
transfer_neglect_late_source = 3000.0
l_max_g = 50
l_max_ur = 150
gauge = synchronous


## Cosmological Parameters
h = 0.67428
A_s = 1.8903e-09
n_s = 0.9383

Omega_cdm = 0.26657662394
Omega_b = 0.04979616143
Omega_k = 0
Omega_fld = 0.0


alpha_s = 0.0
T_cmb = 2.7255
N_ur = 3.044


## Output parameters

output = dTk vTk mPk
root = lcdm_rescaled_base_class_
P_k_max_h/Mpc = 214.46605848506323
z_max_pk = 100.0
z_pk = 99.0
extra metric transfer functions = y

## Geff
#N_ncdm = 0
#m_ncdm = 0.206
#log10_G_eff_nu = -4.477
