# CLASS .ini template for LCDM + mass_nu + Geff code

# Precision params:
k_per_decade_for_pk = 50
k_bao_width = 8
k_per_decade_for_bao = 200
neglect_CMB_sources_below_visibility = 1e-30
transfer_neglect_late_source = 3000.0
l_max_g = 50
l_max_ur = 150
gauge = synchronous

## Cosmological parameters:
h = 0.67428
A_s = 1.987e-9
n_s = 0.9383

Omega_cdm = 0.26657662394
Omega_b = 0.04979616143
Omega_k = 0
alpha_s = 0.0
T_cmb = 2.7255
Omega_fld = 0.0
m_ncdm = 0.06866666666,0.06866666666,0.06866666666
N_ncdm = 3
N_ur = 0.0043999999999999595


## More precision parameters for massive nu:
tol_ncdm_newtonian = 0.0001
tol_ncdm_synchronous = 0.0001
tol_ncdm_bg = 1e-10
l_max_ncdm = 50
ncdm_fluid_approximation = 3 ## Change to 3 for more accuracy
ncdm_fluid_trigger_tau_over_tau_k = 10000.0


## Output parameters
output = dTk vTk mPk
root = lcdm_nu_base_class_
P_k_max_h/Mpc = 214.46605848506323
z_max_pk = 100.0
z_pk = 99.0
extra metric transfer functions = y


## Geff only works with updated CLASS 
#log10_G_eff_nu = -4.477
